/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The JSON schema that matches album info.
 */
export interface AlbumInfo {
  artist: string;
  title: string;
  url: string;
  imageUrl: string;
  tracks: Track[];
  raw: {
    [k: string]: any;
  };
}
export interface Track {
  name: string;
  url: string;
  duration: string;
}
