/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The JSON schema that matches a search result.
 */
export type SearchResult = Artist | Album | BandCampTrack | Fan | Label;

export interface Artist {
  type: "artist";
  name: string;
  url: string;
  imageUrl: string;
  tags: string[];
  genre?: string;
  location: string;
}
export interface Album {
  type: "album";
  name: string;
  url: string;
  imageUrl: string;
  tags: string[];
  releaseDate: string;
  artist: string;
  numTracks: number;
  numMinutes: number;
}
export interface BandCampTrack {
  type: "track";
  name: string;
  url: string;
  imageUrl: string;
  tags: string[];
  releaseDate: string;
  album: string;
  artist: string;
}
export interface Fan {
  type: "fan";
  name: string;
  url: string;
  imageUrl: string;
  tags: string[];
  genre: string;
}
export interface Label {
  type: string;
  name: string;
  url: string;
  imageUrl: string;
  tags: string[];
}
